Readme Updated
ArasLabs/generic-action-item pull request #2
Opened 2019-03-15 19:52 UTC by sampoearas

Usage Steps updated; Added line for 3rd optional import example

2019-03-15 20:37 UTC, EliJDonahue requested changes
It sounds like there may actually be two different use cases for the Usage section - template vs. ad hoc. I think it would make sense to list the steps for both use cases separately. See [the MBOM Export project](https://github.com/ArasLabs/mbom-export) for an example of a project with two use cases.

2019-03-15 20:37 UTC, EliJDonahue commented on README.md
> +[v2.0.1](https://github.com/ArasLabs/generic-action-item/releases/tag/v2.0.1) | Readme usage updated
```suggestion
[v2.0.1](https://github.com/ArasLabs/generic-action-item/releases/tag/v2.0.1) | Readme usage updated. Tested on 11 SP12, 11 SP15.
```

2019-03-15 20:37 UTC, EliJDonahue commented on README.md
> +[v2.0.1](https://github.com/ArasLabs/generic-action-item/releases/tag/v2.0.1) | Tested on 11 SP12, 15
```suggestion
[v2.0.1](https://github.com/ArasLabs/generic-action-item/releases/tag/v2.0.1) | 10 SPx, 11 SPx
```

2019-03-15 20:37 UTC, EliJDonahue commented on README.md
> +* by use of an Action Item Template set up by an Administrator
```suggestion
* Use an Action Item Template set up by an Administrator
```

2019-03-15 20:37 UTC, EliJDonahue commented on README.md
> +  * if notes are needed to close, add to action item via RMB view command
```suggestion
  * If notes are needed to close, add to action item via RMB view command.
```

2019-03-15 20:37 UTC, EliJDonahue commented on README.md
> +  * if new, must save item before using template action
```suggestion
  * If the item is new, save item before using template action.
```

2019-03-15 20:37 UTC, EliJDonahue commented on README.md
> +* Added to an existing DCO item by a user either as ad-hoc or by using an existing template as above
```suggestion
* Add to an existing DCO item by a user, either as ad-hoc or by using an existing template as above.
```

2019-03-15 20:37 UTC, EliJDonahue commented on README.md
> +2. Create New or Open Existing Express DCO
```suggestion
2. Create or open an Express DCO.
```

2019-03-15 20:37 UTC, EliJDonahue commented on README.md
> +1. (Optional) Create Template(s) for action items
```suggestion
1. (Optional) Create Template(s) for action items.
```

2019-03-15 20:37 UTC, EliJDonahue commented on README.md
> +3. Use Action to add from template or add ad hoc using tab
Try to be very specific about how people need to do things. Which action? How do they run that action? Is it a toolbar button, main menu action, or context menu action?

2019-03-15 21:42 UTC, sampoearas reviewed
Added updates for further review.

2019-03-15 21:42 UTC, sampoearas commented on README.md
> +3. Use Action to add from template or add ad hoc using tab
```suggestion
3. Use Actions > Add Action Item From Template to add from template or create a new relationship to an ad hoc item using the Action Item tab (Both methods can be used together)
```

2019-03-15 21:42 UTC, sampoearas commented on README.md
> +4. Fire workflow for action using RMB action in search grid/tab
```suggestion
4. Start Workflow for action using RMB action in the Action Item admin search grid or the Action Item tab on a related item
```

2019-03-18 20:09 UTC, EliJDonahue commented on README.md
> +3. Use Action to add from template or add ad hoc using tab
👍

2019-03-18 20:09 UTC, EliJDonahue commented on README.md
> +4. Fire workflow for action using RMB action in search grid/tab
👍

2019-03-18 20:11 UTC, EliJDonahue approved these changes
👍

2019-03-18 20:13 UTC, EliJDonahue commented
@sampoearas - Go ahead a commit the suggestions you made (I don't have write access to your fork) and then merge this PR.

2019-03-18 20:58 UTC, merged